FROM debian:latest

# Atualiza pacotes e instala dependências
RUN apt-get update && apt-get install -y \
    gettext-base \
    curl \
    bash \
    && rm -rf /var/lib/apt/lists/*

# Baixa e instala o Alertmanager
RUN curl -LO https://github.com/prometheus/alertmanager/releases/download/v0.28.0/alertmanager-0.28.0.linux-amd64.tar.gz && \
    tar -xvf alertmanager-0.28.0.linux-amd64.tar.gz && \
    mv alertmanager-0.28.0.linux-amd64/alertmanager /bin/alertmanager && \
    mv alertmanager-0.28.0.linux-amd64/amtool /bin/amtool && \
    chmod +x /bin/alertmanager /bin/amtool && \
    rm -rf alertmanager-0.28.0.linux-amd64*

# Define o diretório de trabalho
WORKDIR /etc/alertmanager

# Copia o template de configuração
COPY alertmanager.yml.template /etc/alertmanager/alertmanager.yml.template

# Substitui variáveis de ambiente no arquivo de configuração
RUN envsubst < /etc/alertmanager/alertmanager.yml.template > /etc/alertmanager/alertmanager.yml && \
    cat /etc/alertmanager/alertmanager.yml  # Para debug, pode remover depois

# Comando de execução
CMD ["/bin/alertmanager", "--config.file=/etc/alertmanager/alertmanager.yml"]
