FROM alpine:latest

RUN apk add --no-cache \
    gettext \
    curl \
    bash

RUN curl -LO https://github.com/prometheus/alertmanager/releases/download/v0.28.0/alertmanager-0.28.0.linux-amd64.tar.gz && \
    tar -xvf alertmanager-0.28.0.linux-amd64.tar.gz && \
    mv alertmanager-0.28.0.linux-amd64/alertmanager /bin/alertmanager && \
    mv alertmanager-0.28.0.linux-amd64/amtool /bin/amtool && \
    chmod +x /bin/alertmanager /bin/amtool && \
    rm -rf alertmanager-0.28.0.linux-amd64*

WORKDIR /etc/alertmanager

COPY alertmanager.yml.template /etc/alertmanager/alertmanager.yml.template

CMD ["/bin/alertmanager", "--config.file=/etc/alertmanager/alertmanager.yml"]