version: '3.7'

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - node-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring

  watchdog-api:
    build:
      context: .
    container_name: watchdog-api
    ports:
      - "3333:3333"
    networks:
      - monitoring
    depends_on:
      - grafana
  
  client:
    image: request-generator
    build:
      context: ./docker/
      dockerfile: dockerfile
    container_name: request-generator
    depends_on:
      - watchdog-api
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge