version: '3.7'

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/alert.rules:/etc/prometheus/alert.rules
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - node-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring

  watchdog-api:
    build:
      context: .
    container_name: watchdog-api
    ports:
      - "3333:3333"
    networks:
      - monitoring
    depends_on:
      - grafana

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./docker/alert-manager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    ports:
      - "9093:9093"
    networks:
      - monitoring
    depends_on:
      - watchdog-api
  
  client:
    image: request-generator
    build:
      context: ./docker/
      dockerfile: dockerfile
    container_name: request-generator
    depends_on:
      - alertmanager
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge