global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'watchdog-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['watchdog-api:3333']
