{
 "title": "dash-watchdog-api",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(app)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_active_resources{type=\"PipeWrap\",app=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API USE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL MEMORY USED",
     "type": "gauge",
     "description": "Total memory used of the application's total memory.",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (node_memory_total_bytes - node_memory_free_bytes) / node_memory_total_bytes",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "NON-HEAP USED OF TOTAL MEMORY",
     "type": "gauge",
     "description": "non-heap memory used compared to the total memory available in the application.",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(nodejs_nonheap_memory_bytes{app=\"$application\"}) * 100 / sum(node_memory_total_bytes{app=\"$application\"})",
       "legendFormat": "non-heap"
      }
     ]
    },
    {
     "title": "NON-HEAP X MEMORY USED",
     "type": "gauge",
     "description": "Percentage of non-heap memory in the application's used memory",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(nodejs_nonheap_memory_bytes) * 100 / sum(node_memory_total_bytes - node_memory_free_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HEAP USED ",
     "type": "gauge",
     "description": "Heap memory used",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(nodejs_heap_size_used_bytes{app=\"$application\"} / nodejs_heap_size_total_bytes{app=\"$application\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LOAD AVERAGE",
     "type": "timeseries",
     "description": "CPU usage average",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "node_load1", "legendFormat": "Load average" },
      {
       "expr": "count(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"})",
       "legendFormat": "CPU core size"
      }
     ]
    },
    {
     "title": "CPU UTILIZATION",
     "type": "timeseries",
     "description": "Overall CPU usage of the system and a specific process.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
       "legendFormat": "System CPU usage"
      },
      {
       "expr": "rate(process_cpu_user_seconds_total{app=\"watchdog-api\"}[1m]) + rate(process_cpu_system_seconds_total{app=\"watchdog-api\"}[1m])",
       "legendFormat": "Process CPU usage"
      }
     ]
    },
    {
     "title": "MEMORY IN USE",
     "type": "timeseries",
     "description": "Memory in use vs free memory",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_memory_Active_bytes / node_memory_MemTotal_bytes) * 100",
       "legendFormat": "memory in use"
      }
     ]
    }
   ]
  },
  {
   "title": "API RED",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL REQUEST",
     "type": "stat",
     "description": "Number of requests in the last minute.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_requests_total[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ERROR 500",
     "type": "stat",
     "description": "Number of errors 500 in the last minute",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(logback_events_total{app=\"$application\", status=\"500\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AVERAGE LATENCY",
     "type": "timeseries",
     "description": "Average latency per minute",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{app=\"$application\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{app=\"$application\"}[1m])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_seconds_bucket{app=\"$application\"}[1m])) by (le))",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{app=\"$application\"}[1m])) by (le))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.25, sum(rate(http_request_duration_seconds_bucket{app=\"$application\"}[1m])) by (le))",
       "legendFormat": "25%"
      }
     ]
    },
    {
     "title": "ERROR RATE",
     "type": "timeseries",
     "description": "Error rate in the last 5 minutes",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(logback_events_total{app=\"$application\", status=\"400\"}[5m])) / sum(rate(logback_events_total{app=\"$application\"}[5m]))",
       "legendFormat": "400"
      },
      {
       "expr": "sum(rate(logback_events_total{app=\"$application\", status=\"404\"}[5m])) / sum(rate(logback_events_total{app=\"$application\"}[5m]))",
       "legendFormat": "404"
      },
      {
       "expr": "sum(rate(logback_events_total{app=\"$application\", status=\"500\"}[5m])) / sum(rate(logback_events_total{app=\"$application\"}[5m]))",
       "legendFormat": "500"
      }
     ]
    },
    {
     "title": "RESPONSE TIME",
     "type": "timeseries",
     "description": "Last minute response time",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_request_duration_seconds_sum{app=\"$application\"}[1m]) / rate(http_request_duration_seconds_count{app=\"$application\"}[1m])",
       "legendFormat": "{{route}} {{method}} {{status}}"
      }
     ]
    },
    {
     "title": "TOTAL ERRORS X TOTAL REQUESTS",
     "type": "timeseries",
     "description": "Calculate the percentage of errors based on the number of errors and requests in the last 1 minutes",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(logback_events_total{app=\"$application\"}[1m])) / sum(rate(http_requests_total{app=\"$application\"}[1m])) * 100",
       "legendFormat": "Percentage of errors"
      }
     ]
    },
    {
     "title": "REQUEST COUNT",
     "type": "timeseries",
     "description": "Number of requests per endpoint in the last minute.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(http_request_duration_seconds_count{app=\"$application\", method=\"GET\", route=\"/\"}[1m]))",
       "legendFormat": "GET: / "
      },
      {
       "expr": "sum(increase(http_request_duration_seconds_count{app=\"$application\", method=\"POST\", route=\"/\"}[1m]))",
       "legendFormat": "POST: / "
      },
      {
       "expr": "sum(increase(http_request_duration_seconds_count{app=\"$application\", route=\"/session\"}[1m]))",
       "legendFormat": "/session"
      },
      {
       "expr": "sum(increase(http_request_duration_seconds_count{app=\"$application\", route=\"/latency\"}[1m]))",
       "legendFormat": "/latency"
      }
     ]
    },
    {
     "title": "AVERAGE DURATION OF REQUEST",
     "type": "timeseries",
     "description": "Average duration of requests in the last minute",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_request_duration_seconds_sum{app=\"$application\", method=\"GET\", route=\"/\"}[1m]) / rate(http_request_duration_seconds_count{app=\"$application\", method=\"GET\", route=\"/\"}[1m])",
       "legendFormat": "{{method}}: /"
      },
      {
       "expr": "rate(http_request_duration_seconds_sum{app=\"$application\", method=\"POST\", route=\"/\"}[1m]) / rate(http_request_duration_seconds_count{app=\"$application\", method=\"POST\", route=\"/\"}[1m])",
       "legendFormat": "{{method}}: /"
      },
      {
       "expr": "rate(http_request_duration_seconds_sum{app=\"$application\", method=\"POST\", route=\"/session\"}[1m]) / rate(http_request_duration_seconds_count{app=\"$application\", method=\"POST\", route=\"/session\"}[1m])",
       "legendFormat": "{{route}}"
      },
      {
       "expr": "rate(http_request_duration_seconds_sum{app=\"$application\", method=\"GET\", route=\"/latency\"}[1m]) / rate(http_request_duration_seconds_count{app=\"$application\", method=\"GET\", route=\"/latency\"}[1m])",
       "legendFormat": "{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API BASIC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "UPTIME",
     "type": "stat",
     "description": "How long has the api been running?",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(time() - process_start_time_seconds{app=\"$application\", instance=\"$instance\"}) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "START TIME",
     "type": "stat",
     "description": "Time the application was started",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{app=\"$application\", instance=\"$instance\"} * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "USERS LOGGED",
     "type": "stat",
     "description": "Approximate number of users logged in within a minute",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(auth_user_success_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AUTH ERRORS",
     "type": "stat",
     "description": "Approximate number of authentication errors in a period of one minute",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(auth_user_error_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ERROR LOG",
     "type": "timeseries",
     "description": "Errors recorded in the last fice minutes",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(logback_events_total{level=\"error\", app=\"$application\"}[5m]))",
       "legendFormat": "error"
      }
     ]
    }
   ]
  }
 ]
}